version: '3'

services:
  hm-web:
    image: hm-api-image
    container_name: hm-api-conatiner
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/hm-api
    ports:
      - "8083:8080"
